# Generated by Django 2.0 on 2021-09-13 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(help_text="Describe it's way of life,gestation period,lifespan,habitat and it's food")),
                ('image', models.ImageField(upload_to='images/')),
                ('sightloc', models.TextField(help_text='Where can this be sighted in Uganda?')),
            ],
        ),
        migrations.CreateModel(
            name='CarHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('carimage', models.ImageField(upload_to='images/')),
                ('carlocation', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('about', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fbody', models.TextField()),
                ('Image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('Hname', models.CharField(max_length=130)),
                ('location', models.CharField(max_length=140)),
                ('Image', models.ImageField(upload_to='images/')),
                ('website', models.URLField()),
                ('Services', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='TourCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=200)),
                ('Cimage', models.ImageField(upload_to='images/')),
                ('Services', models.TextField()),
                ('location', models.TextField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Tourguides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=120)),
                ('profileimage', models.ImageField(upload_to='images/')),
                ('phonenumber', models.IntegerField()),
                ('Bio', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='images/')),
                ('Date', models.DateField()),
                ('desc', models.CharField(max_length=200)),
                ('Inclusions', models.TextField()),
                ('Exclusions', models.TextField()),
                ('duration', models.CharField(help_text='Specify trip duration in form  of 3days/2nights', max_length=150)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Triptype', models.CharField(choices=[('BDT', 'Budget'), ('MRE', 'Mid-Range'), ('LUX', 'Luxury')], max_length=8)),
                ('accmtype', models.CharField(choices=[('Camping', 'Camping'), ('Hotel', 'Hotel'), ('Hostel', 'Hostel')], max_length=10)),
                ('paymentmthd', models.TextField(help_text='Describe the mode of payment, if mobile money,send in the mobile money details ')),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('tweetedby', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('tweetedOn', models.DateTimeField(default=datetime.datetime.now)),
                ('runyatweet', models.TextField()),
                ('lugatweet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('link', models.URLField()),
                ('runya', models.TextField()),
                ('luga', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
