# Generated by Django 2.0 on 2021-09-13 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xploreapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='threadurl',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
